# Generated by Django 4.2.3 on 2023-10-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255, unique=True)),
                ("email_id", models.EmailField(max_length=254, unique=True)),
                (
                    "company_code",
                    models.CharField(
                        blank=True,
                        help_text="Length should be 5 characters. 1st & 2nd characters should be alphabets, 3rd & 4th characters should be numbers, and 5th character should be 'E' or 'N'.",
                        max_length=5,
                        null=True,
                        unique=True,
                    ),
                ),
                ("strength", models.PositiveIntegerField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
